version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - DATABASE_HOST=18.191.201.186
      - DATABASE_NAME=tilt
      - DATABASE_PASSWORD=6hK3&ABsYZ8S6Z
      - DATABASE_USER=tilt
      - DEBUG=0
      - ENVIRONMENT=development
      - SECRET_KEY=593zDT!%DvVUan%husB73vYG3Sd3z4QM5
      - SENDGRID_API_KEY=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
    ports:
      - 8000:8000
    volumes:
      - .:/app
