version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DEBUG=1
      - SECRET_KEY=Be8e94Q@A#P2qW6MAWSD8Ar@nc!qV
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
